#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    i=1
    s=1
    while i < 11:
        s=n*i
        print(n, "x", i, "=", s)
        i+=1
